Feature/create user
wolox-training/sr-react pull request #3
Opened 2021-02-19 16:15 UTC by santiagoRD

## Summary

create user service integrated with useRequest, added loader and error message on post failure

## Screenshots

<img width="1759" alt="integration" src="https://user-images.githubusercontent.com/39193671/108530381-8a45d480-72a3-11eb-90cd-385787ddf0d5.png">

## Trello Card

https://trello.com/c/NXhgOMTJ/91-sign-up-ii-integration

2021-02-19 20:45 UTC, CrisVega08 requested changes

2021-02-19 20:45 UTC, CrisVega08 commented on src/config/api.js
> +const baseURL = 'https://books-training-rails.herokuapp.com/api/v1';
Use environment variable

2021-02-19 20:45 UTC, CrisVega08 commented on src/types/types.ts
> +  locale?: string;
Is optional ?

2021-02-22 19:59 UTC, manuelgomezo commented on src/services/UserService.ts
> +const UserService = {
I really like this way to export the service!

2021-02-23 22:19 UTC, CrisVega08 requested changes

2021-02-23 22:19 UTC, CrisVega08 commented on .env
> +REACT_APP_BASE_URL = 'https://books-training-rails.herokuapp.com/api/v1'
This file must be added to .gitignore

2021-02-24 14:28 UTC, manuelgomezo approved these changes

2021-02-24 14:28 UTC, manuelgomezo commented on src/screens/SignUp/index.tsx
>  import wLogo from '../../assets/wLogo.png';
I believe you can use:

`import wLogo from 'assets/wLogo.png';`

2021-02-27 00:02 UTC, CrisVega08 approved these changes

2021-02-27 01:03 UTC, merged