Feature/sign up test
wolox-training/sr-react pull request #4
Opened 2021-02-22 22:09 UTC by santiagoRD

## Summary

added tests to validate signup feature

## Screenshots

<img width="1792" alt="tests" src="https://user-images.githubusercontent.com/39193671/108776384-559a7d00-7530-11eb-98f4-9aafaf4d36a7.png">

## Trello Card

https://trello.com/c/WsjkJiDM/103-tests-de-sign-up

2021-02-23 16:42 UTC, manuelgomezo commented on src/screens/SignUp/index.tsx
> +        {state && (
I'm not sure if this is the best way to handle successful response. Better way for me it's using withPostSuccess function and setting a success state and checking it

2021-02-23 16:43 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +  rest.post(`${process.env.REACT_APP_BASE_URL}/users`, (req, res, ctx) =>
put this and server declaration outside the describe function.

2021-02-23 16:44 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +  afterEach(() => server.resetHandlers());
same for this. move outside.

2021-02-23 16:46 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +    userEvent.click(screen.getByRole('textbox', { name: /SignUp:email/ }));
Why are you testing "onSubmit" when you clicked a text box? You must click the submit button.

2021-02-23 16:46 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +    userEvent.click(screen.getByRole('textbox', { name: /SignUp:email/ }));
same here

2021-02-23 16:48 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +      expect((screen.getByLabelText(/SignUp:email/i) as HTMLInputElement).value).toBe('invalid-email');
`expect(await screen.findByText(/SignUp:email/i)).toBeInTheDocument();` its another better way to do that

2021-02-23 16:49 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +      expect(onSubmit).not.toBeCalled();
Did you try this function in the opposite case? when the fields are all correct? I think the onSubmit as you declared it is not mocked

2021-02-24 13:53 UTC, CrisVega08 requested changes

2021-02-24 13:53 UTC, CrisVega08 commented on src/screens/SignUp/signUp.test.tsx
> +
What do you think about this 

```
const server = setupServer(rest.post('/users', (_, res, ctx) => res(ctx.json({mockResponse}))));

beforeAll(() => server.listen());
beforeEach(() => render(<signUp>))
afterEach(() => server.resetHandlers());
afterAll(() => {
  server.close();
  cleanup();
});
```

Where mockResponse is similar to :

```
  id: xxx,
  firstName: '',
  lastName: '',
  email: '',
  locale: ''
```

2021-02-24 13:53 UTC, CrisVega08 commented on src/screens/SignUp/signUp.test.tsx
> +      rest.post(`${process.env.REACT_APP_BASE_URL}/users`, (req, res, ctx) =>
I think environment variable is unnecessary

2021-02-27 00:03 UTC, CrisVega08 approved these changes

2021-03-01 01:42 UTC, merged