feature(Routing): adding app routes
wolox-training/sr-react pull request #5
Opened 2021-02-23 13:53 UTC by santiagoRD

## Summary

Adding app routes (signup and login)

## Screenshots

<img width="1792" alt="login" src="https://user-images.githubusercontent.com/39193671/108852925-288fae00-75b4-11eb-977f-8c5e8f76dc91.png">
<img width="1777" alt="signup" src="https://user-images.githubusercontent.com/39193671/108852947-2d546200-75b4-11eb-988d-f6aab36b9406.png">

## Trello Card

https://trello.com/c/UpPMHQXi/93-routing-i-router

2021-02-24 13:57 UTC, CrisVega08 requested changes

2021-02-24 13:57 UTC, CrisVega08 commented on src/routes/index.tsx
> +        <Route path="/sign_up" component={SignUp} />
You can create an object Routes and use here

```suggestion
        <Route path="ROUTES.signUp" component={SignUp} />
```
```
export const ROUTES = {
  signUp: '/sign_up',
  login: '/'
};
```

2021-02-24 13:57 UTC, CrisVega08 commented on src/screens/Login/index.tsx
> +    <div>
Unnecessary div

2021-02-27 00:04 UTC, CrisVega08 approved these changes

2021-03-01 14:19 UTC, manuelgomezo approved these changes

2021-03-01 22:25 UTC, merged