Feature/login
wolox-training/sr-react pull request #6
Opened 2021-02-25 15:25 UTC by santiagoRD

## Summary

Create Login screen, add validations and integration with service and create tests

## Screenshots

<img width="1792" alt="Captura de Pantalla 2021-02-25 a la(s) 10 20 25 a  m" src="https://user-images.githubusercontent.com/39193671/109174860-3c254b00-7753-11eb-9568-35184162510f.png">

## Trello Card

https://trello.com/c/DvNtnkGz/80-login

2021-03-01 14:43 UTC, manuelgomezo requested changes

2021-03-01 14:43 UTC, manuelgomezo commented on src/components/Input/index.tsx
> +function InputText({ inputRef, label, errorMessage, name, i18nKey, ...rest }: Props) {
This prop seems strange to me, I would prefer that you send it directly in the "name" prop

2021-03-01 14:43 UTC, manuelgomezo commented on src/components/Input/index.tsx
> +        {errorMessage ? i18next.t(`${i18nKey}:${errorMessage}`) : ''}
same for it

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/Login/index.tsx
> +      console.log(data, headers);
Delete this

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/Login/index.tsx
> +import { ERROR_MESSAGES, I18N_CONFIG, LOGIN_FIELDS, SIGNUP_BUTTONS, SUCCESS_MESSAGES } from 'constants/index';
check if you can import without index file declaration: ... from 'constants'

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/Login/login.test.tsx
> +import Login from '.';
`import Login from  './index';`

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/Login/index.tsx
> +          onClick={() => history.push('/sign_up')}
`history.push(paths.signUp)`

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/SignUp/index.tsx
> +          onClick={() => history.push('/')}
`history.push(routes.home)`

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +  history.push('/sign_up');
Use of routes constants

2021-03-01 14:43 UTC, manuelgomezo commented on src/screens/SignUp/signUp.test.tsx
> +        <Route path="/sign_up">
Use of routes constants

2021-03-02 13:45 UTC, CrisVega08 requested changes

2021-03-02 13:45 UTC, CrisVega08 commented on src/config/api.js
> +export const baseURL = process.env.REACT_APP_BASE_URL || '';
Why do you need export baseURL if you can access with process.env?

2021-03-02 13:45 UTC, CrisVega08 commented on src/hooks/useRequest.ts
> +type Success<D, HEADERS> = (data?: D, headers?: HEADERS) => void;
```suggestion
type Success<D, H> = (data?: D, headers?: H) => void;
```

2021-03-02 13:45 UTC, CrisVega08 commented on src/hooks/useRequest.ts
>    const response = await request(values);
```suggestion
  const { ok, data, headers, problem } = await request(values);
```

2021-03-02 13:45 UTC, CrisVega08 commented on src/screens/Login/index.tsx
> +import { ERROR_MESSAGES, I18N_CONFIG, LOGIN_FIELDS, SIGNUP_BUTTONS, SUCCESS_MESSAGES } from 'constants/index';
```suggestion
import { ERROR_MESSAGES, I18N_CONFIG, LOGIN_FIELDS, SIGNUP_BUTTONS, SUCCESS_MESSAGES } from 'constants';
```

2021-03-02 13:45 UTC, CrisVega08 commented on src/screens/Login/login.test.tsx
> +rest.post(`${baseURL}/users/sign_in`, (_, res, ctx) =>
```suggestion
rest.post('/users/sign_in', (_, res, ctx) =>
```

2021-03-02 13:45 UTC, CrisVega08 commented on src/screens/SignUp/index.tsx
> +      history.push('/');
use constante Routes

2021-03-04 14:19 UTC, CrisVega08 approved these changes

2021-03-04 14:50 UTC, manuelgomezo approved these changes

2021-03-04 18:41 UTC, merged