Feature/session management
wolox-training/sr-react pull request #7
Opened 2021-02-25 17:34 UTC by santiagoRD

## Summary

Create Home component with a logout button, and create tests to validate redirection after click in logout button. 

## Screenshots

<img width="1706" alt="Home" src="https://user-images.githubusercontent.com/39193671/109192735-9929fc80-7765-11eb-8e54-14082a15f90e.png">

## Trello Card

https://trello.com/c/GrFUn3Du/83-session-management-logout

2021-03-01 14:46 UTC, manuelgomezo requested changes

2021-03-01 14:46 UTC, manuelgomezo commented on src/constants/index.js
>  export const ROUTES = {
I believe you can move this to another single file /constants/routes.ts

2021-03-01 14:46 UTC, manuelgomezo commented on src/screens/Home/index.tsx
> +    localStorage.removeItem('token');
Move this function inside utility file. `utils/session.ts`

2021-03-01 14:46 UTC, manuelgomezo commented on src/screens/Login/index.tsx
> +      localStorage.setItem('token', token);
same for it.

2021-03-02 13:51 UTC, CrisVega08 requested changes

2021-03-02 13:51 UTC, CrisVega08 commented on public/index.html
> +    <link
Import font in scss file

2021-03-02 13:51 UTC, CrisVega08 commented on src/config/api.js
>  api.addResponseTransform(response => {
```suggestion
api.addResponseTransform(({data, headers}) => {
```

2021-03-02 13:51 UTC, CrisVega08 commented on src/routes/index.tsx
>          <Route path={ROUTES.signUp} component={SignUp} />
You can improve your const Routes adding path, component and other properties. And here you can loop it for create dynamic routes
```
Routes.map(({component, path , exact}) => <Route path={path} component={component} />)

```

2021-03-05 13:22 UTC, CrisVega08 approved these changes

2021-03-05 20:41 UTC, manuelgomezo approved these changes

2021-03-08 12:56 UTC, merged